spring.application.name=Rent_Car

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/rentcar_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# JPA Hibernate

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
# JWT Configuration
app.jwt.secret=MaCleSecreteTresLongueEtComplexePourMonProjetRentCar2026
app.jwt.expiration=86400000
# Stripe Configuration
stripe.secret.key=dummy_key_for_github
stripe.webhook.secret=ddededed
# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
# Server
server.port=8089